### ISSUE TITLE
Not running on Opensuse Leap 15

### ISSUE THREAD

**Issue by ingmarcosp** [flathub/org.librepcb.LibrePCB#1]
I just install the program and I have this problem traing to run it:

~>flatpak run org.librepcb.LibrePCB                                                                   
bwrap: Can't find source path /tmp/.X11-unix/X2: No such file or directory

maybe you can help me or fixit, thanks!

**Comment by TingPing** [comment]
Sounds like your host has a bad `$DISPLAY` env var.

**Comment by ingmarcosp** [comment]
yup, now is working, sorry, and thanks for the answer!!
