### ISSUE TITLE
Flathub verification

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.librepcb.LibrePCB#16]
Since you as the author maintain the Flathub package, you could verify it here:

https://flathub.org/apps/manage/org.librepcb.LibrePCB

You would need to create https://librepcb.org/.well-known/org.flathub.VerifiedApps.txt with a token given on the page above. This would result in such a badge:

![image](https://github.com/flathub/org.librepcb.LibrePCB/assets/3226457/079b5095-bba7-4a0f-addc-44c65dece9ff)

**Comment by ubruhin** [comment]
Thanks for the hint, It is now verified! :muscle: 

![image](https://github.com/flathub/org.librepcb.LibrePCB/assets/5374821/27d1aaa2-c22d-4478-a938-dbada32c1778)
